## Import Packages

In [40]:
!pip install dask

Requirement already satisfied: dask in /usr/local/lib/python3.12/dist-packages (2026.3.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask) (8.3.3)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask) (26.1)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask) (0.12.1)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask) (1.0.0)

In [41]:
import numpy as np
import pandas as pd
import dask.dataframe as dd
import matplotlib.pyplot as plt
import seaborn as sns

## Load Data

In [42]:
# paths for the three dfs

df_jan_path = "/kaggle/input/datasets/elemento/nyc-yellow-taxi-trip-data/yellow_tripdata_2016-01.csv"
df_feb_path = "/kaggle/input/datasets/elemento/nyc-yellow-taxi-trip-data/yellow_tripdata_2016-02.csv"
df_mar_path = "/kaggle/input/datasets/elemento/nyc-yellow-taxi-trip-data/yellow_tripdata_2016-03.csv"

- Based on the exploratory data analysis (EDA) of NYC Yellow Taxi trips, we identified outliers in the data. I selected specific columns that are useful for demand prediction, and these columns also contain outliers. Therefore, I need to remove the outliers from these specific columns.
- Columns are 'trip_distance', 'pickup_longitude',
       'pickup_latitude','dropoff_longitude', 'dropoff_latitude', 'fare_amount'

In [43]:
# load the dataframes

df_jan = dd.read_csv(df_jan_path, assume_missing=True, usecols= ['trip_distance', 'tpep_pickup_datetime', 'pickup_longitude',
       'pickup_latitude','dropoff_longitude', 'dropoff_latitude', 'fare_amount'], parse_dates=["tpep_pickup_datetime"])

df_feb = dd.read_csv(df_feb_path, assume_missing=True, usecols= ['trip_distance', 'tpep_pickup_datetime', 'pickup_longitude',
       'pickup_latitude','dropoff_longitude', 'dropoff_latitude', 'fare_amount'], parse_dates=["tpep_pickup_datetime"])


df_mar = dd.read_csv(df_mar_path, assume_missing=True, usecols= ['trip_distance', 'tpep_pickup_datetime', 'pickup_longitude',
       'pickup_latitude','dropoff_longitude', 'dropoff_latitude', 'fare_amount'], parse_dates=["tpep_pickup_datetime"])

In [44]:
# concat the three dataframes as one

df_final = dd.concat([df_jan, df_feb, df_mar], axis=0) # axis =0 means It works vertically (up and down).

In [45]:
df_final.head()

,tpep_pickup_datetime,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,fare_amount
0,2016-01-01,1.10,-73.990372,40.734695,-73.981842,40.732407,7.5
1,2016-01-01,4.90,-73.980782,40.729912,-73.944473,40.716679,18.0
2,2016-01-01,10.54,-73.984550,40.679565,-73.950272,40.788925,33.0
3,2016-01-01,4.75,-73.993469,40.718990,-73.962242,40.657333,16.5
4,2016-01-01,1.76,-73.960625,40.781330,-73.977264,40.758514,8.0

### **New york bounding box:**
min_latitude = 40.60
max_latitude = 40.85
min_longitude = -74.05
max_longitude = -73.70

In [46]:
# set the values of coordinates

min_latitude = 40.60
max_latitude = 40.85
min_longitude = -74.05
max_longitude = -73.70

In [47]:
# fare amount column
fare_amount = df_final["fare_amount"].compute()

# trip distance column
trip_distance = df_final["trip_distance"].compute()

In [48]:
fare_amount.shape[0]/10000000

3.4499859

In [49]:
## Percentile of fare amount
percentiles=np.arange(0.991,1,0.001)
fare_amount.quantile(percentiles)

0.991        52.00
0.992        52.00
0.993        52.00
0.994        52.00
0.995        54.00
0.996        58.50
0.997        63.00
0.998        69.00
0.999        81.00
1.000    429496.72
Name: fare_amount, dtype: float64

In [50]:
max_fare_amount_val = fare_amount.quantile(percentiles).iloc[-2].item()
min_fare_amount_val = 0.50

print(min_fare_amount_val)
print(max_fare_amount_val)

0.5
81.0

In [51]:
trip_distance.quantile(percentiles)

0.991          18.80
0.992          19.00
0.993          19.30
0.994          19.63
0.995          20.04
0.996          20.51
0.997          21.10
0.998          21.90
0.999          24.43
1.000    19072628.80
Name: trip_distance, dtype: float64

In [52]:
# percentile values for trip_distance

min_trip_distance_val = 0.25
max_trip_distance_val = trip_distance.quantile(percentiles).iloc[-2].item()

print(min_trip_distance_val)
print(max_trip_distance_val)

0.25
24.43

## Remove Outlier from the location data

In [53]:
# select data points within the given ranges

df_final = df_final.loc[(df_final["pickup_latitude"].between(min_latitude, max_latitude, inclusive="both")) & 
(df_final["pickup_longitude"].between(min_longitude, max_longitude, inclusive="both")) & 
(df_final["dropoff_latitude"].between(min_latitude, max_latitude, inclusive="both")) & 
(df_final["dropoff_longitude"].between(min_longitude, max_longitude, inclusive="both")), :]

## Remove Outliers from the Fare Amount data and Distance

In [54]:
df_final = df_final.loc[(df_final["fare_amount"].between(min_fare_amount_val,max_fare_amount_val,inclusive="both")) & 
(df_final["trip_distance"].between(min_trip_distance_val,max_trip_distance_val,inclusive="both"))]

## Remove Outliers from the Distance data

In [55]:
df_final = df_final.loc[(df_final["fare_amount"].between(min_fare_amount_val,max_fare_amount_val,inclusive="both")) & 
(df_final["trip_distance"].between(min_trip_distance_val,max_trip_distance_val,inclusive="both"))]

## Save After Removing Outlier

In [56]:
# save the pickup coordinates dataset
import os

dir_path = "/kaggle/working/data/interim/"
file_path = os.path.join(dir_path, "location_data.csv")
pickup_coord_dataset = df_final.loc[:,['tpep_pickup_datetime','pickup_latitude','pickup_longitude']]

In [57]:
# form the dataset

pickup_coord_dataset = df_final.loc[:,['tpep_pickup_datetime','pickup_latitude','pickup_longitude']].compute()

print("Shape of the dataset is ", pickup_coord_dataset.shape)

Shape of the dataset is  (33234199, 3)

In [58]:
import os
os.makedirs(dir_path, exist_ok=True)

In [59]:
pickup_coord_dataset.to_csv(file_path, index=False)

## Making The Regions

In [86]:
import pandas as pd
from sklearn.cluster import MiniBatchKMeans
from sklearn.preprocessing import StandardScaler

In [87]:
df_reader=pd.read_csv("/kaggle/working/data/interim/location_data.csv",chunksize=100000, usecols=["pickup_latitude","pickup_longitude"])

In [88]:
# train the standard scaler

scaler = StandardScaler()

for chunk in df_reader:
    # fit the scaler
    scaler.partial_fit(chunk)

In [89]:
# 1. Re-initialize the iterator (since cell 73 consumed it completely)
df_reader = pd.read_csv("/kaggle/working/data/interim/location_data.csv", chunksize=100000, usecols=["pickup_latitude", "pickup_longitude"])

# 2. Train the MiniBatchKMeans model
mini_batch = MiniBatchKMeans(n_clusters=30, n_init=10, random_state=42)
for chunk in df_reader:
    scaled_chunk = scaler.transform(chunk)
    mini_batch.partial_fit(scaled_chunk)

# 3. Access centroids
mini_batch.cluster_centers_

array([[ 1.94149572,  0.6614905 ],
       [-0.13980742, -0.07596928],
       [-1.99721801,  1.44528196],
       [-3.83635934,  5.15118517],
       [-1.16343866, -0.81227839],
       [ 0.42137614, -0.13488625],
       [ 0.72209007,  2.8610836 ],
       [-0.52924948, -0.39015448],
       [ 1.07003845,  0.56520318],
       [-2.24451716, -0.3303071 ],
       [-1.00166487, -0.4036074 ],
       [ 1.16185672, -0.10175947],
       [-0.08902033, -0.55920139],
       [ 0.31820801,  1.59046972],
       [-0.04552948, -0.25372558],
       [ 0.20846098, -0.35389222],
       [-1.31780812,  0.52314378],
       [ 2.79102906,  0.81932304],
       [ 0.28712745,  0.12935608],
       [ 0.73099844, -0.27639436],
       [-1.53772972, -1.0082658 ],
       [ 0.67692302,  0.39844824],
       [-0.76412025, -0.74701446],
       [ 1.62394033,  0.1378545 ],
       [-3.07963657, -0.43385234],
       [ 0.3506753 , -0.54018812],
       [-0.57100818, -0.17842182],
       [-0.38830582, -0.76072368],
       [-2.66479788,  0.4240573 ],
       [-0.12982563,  1.03071807]])

In [90]:
scaler.inverse_transform(mini_batch.cluster_centers_)

array([[ 40.80392392, -73.94975046],
       [ 40.74726528, -73.97685385],
       [ 40.69670159, -73.92094427],
       [ 40.64663525, -73.78474354],
       [ 40.7193993 , -74.00391496],
       [ 40.7625422 , -73.97901919],
       [ 40.77072843, -73.8689102 ],
       [ 40.73666362, -73.9884009 ],
       [ 40.78020052, -73.95328925],
       [ 40.68996945, -73.98620137],
       [ 40.72380321, -73.98889533],
       [ 40.78270006, -73.9778017 ],
       [ 40.74864784, -73.99461378],
       [ 40.75973368, -73.91560827],
       [ 40.74983178, -73.98338682],
       [ 40.75674608, -73.98706818],
       [ 40.71519695, -73.95483503],
       [ 40.82705049, -73.94394974],
       [ 40.75888759, -73.96930766],
       [ 40.77097094, -73.98421995],
       [ 40.70921009, -74.01111796],
       [ 40.76949887, -73.95941789],
       [ 40.73026981, -74.00151635],
       [ 40.79527921, -73.96899532],
       [ 40.66723527, -73.9900069 ],
       [ 40.76061753, -73.993915  ],
       [ 40.73552684, -73.98061923],
       [ 40.74050049, -74.0020202 ],
       [ 40.67852828, -73.95847669],
       [ 40.74753701, -73.93618047]])

In [91]:
final_df=pd.read_csv("/kaggle/working/data/interim/location_data.csv")

In [92]:
final_df.head()

  tpep_pickup_datetime  pickup_latitude  pickup_longitude
0  2016-01-01 00:00:00        40.734695        -73.990372
1  2016-01-01 00:00:00        40.729912        -73.980782
2  2016-01-01 00:00:00        40.679565        -73.984550
3  2016-01-01 00:00:00        40.718990        -73.993469
4  2016-01-01 00:00:00        40.781330        -73.960625

In [93]:
# prediction 
scaled_location_subset = scaler.transform(final_df.iloc[:, 1:])


scaled_location_subset

# get the cluster predictions

cluster_predictions = mini_batch.predict(scaled_location_subset)

cluster_predictions.shape

(33234199,)

In [103]:
# save the cluster predictions in data

# Save the cluster predictions directly into your Pandas DataFrame
final_df['region'] = cluster_predictions
time_series_data = final_df.drop(columns=["pickup_latitude","pickup_longitude"])

save_path = "/kaggle/working/data/interim/time_series.csv"

time_series_data.to_csv(save_path, index=False)

In [77]:
# import shutil 

# shutil.rmtree("/kaggle/working/data/interim/time_series.csv")

* Time Series Data

In [124]:
time_series_data=pd.read_csv("/kaggle/working/data/interim/time_series.csv")

In [128]:
time_series_data.head()

  tpep_pickup_datetime  region
0  2016-01-01 00:00:00       7
1  2016-01-01 00:00:00      26
2  2016-01-01 00:00:00       9
3  2016-01-01 00:00:00      10
4  2016-01-01 00:00:00       8

In [129]:
time_series_data['tpep_pickup_datetime'] = pd.to_datetime(time_series_data['tpep_pickup_datetime'])

In [130]:
time_series_data.set_index('tpep_pickup_datetime', inplace=True)

time_series_data

                      region
tpep_pickup_datetime
2016-01-01 00:00:00        7
2016-01-01 00:00:00       26
2016-01-01 00:00:00        9
2016-01-01 00:00:00       10
2016-01-01 00:00:00        8
...                      ...
2016-03-31 21:43:11        3
2016-03-20 08:45:16        3
2016-03-20 08:59:21        3
2016-03-26 03:02:32       19
2016-03-20 08:50:24        3

[33234199 rows x 1 columns]

In [132]:
region_group=time_series_data.groupby("region")

In [133]:
time_series_data.isna().sum()

region    0
dtype: int64

In [134]:
# resample the time series in 15 minute intervals

resampled_data = (
    region_group['region']
    .resample("15min")
    .count()
)

resampled_data

region  tpep_pickup_datetime
0       2016-01-01 00:00:00      58
        2016-01-01 00:15:00     120
        2016-01-01 00:30:00     149
        2016-01-01 00:45:00     160
        2016-01-01 01:00:00     187
                               ...
29      2016-03-31 22:45:00      14
        2016-03-31 23:00:00      17
        2016-03-31 23:15:00      18
        2016-03-31 23:30:00      13
        2016-03-31 23:45:00      14
Name: region, Length: 262080, dtype: int64

In [135]:

resampled_data.name = "total_pickups"

In [136]:
resampled_data = resampled_data.reset_index(level=0)

resampled_data

                      region  total_pickups
tpep_pickup_datetime
2016-01-01 00:00:00        0             58
2016-01-01 00:15:00        0            120
2016-01-01 00:30:00        0            149
2016-01-01 00:45:00        0            160
2016-01-01 01:00:00        0            187
...                      ...            ...
2016-03-31 22:45:00       29             14
2016-03-31 23:00:00       29             17
2016-03-31 23:15:00       29             18
2016-03-31 23:30:00       29             13
2016-03-31 23:45:00       29             14

[262080 rows x 2 columns]

In [137]:

# zeros in the data

(resampled_data['total_pickups'] == 0).sum()

np.int64(3668)

In [138]:
epsilon_val = 10

resampled_data.replace({'total_pickups': {0 : epsilon_val}}, inplace=True)

In [140]:

(resampled_data['total_pickups'] == 0).sum()

np.int64(0)

In [141]:

from sklearn.metrics import mean_absolute_percentage_error

In [142]:
window_values = list(range(3,11,1))
window_values

[3, 4, 5, 6, 7, 8, 9, 10]

In [143]:
def calculate_best_window_value(windows):
    for window in windows:
        ind = window - 1
        y_pred = resampled_data['total_pickups'].rolling(window=window).mean().values[ind:]
        y = resampled_data['total_pickups'].values[ind:]
        error = mean_absolute_percentage_error(y, y_pred)
        print(f"For window value {window}, the MAPE is {error:.2f}")

In [144]:

calculate_best_window_value(window_values)

For window value 3, the MAPE is 0.20
For window value 4, the MAPE is 0.24
For window value 5, the MAPE is 0.28
For window value 6, the MAPE is 0.31
For window value 7, the MAPE is 0.35
For window value 8, the MAPE is 0.39
For window value 9, the MAPE is 0.42
For window value 10, the MAPE is 0.46

In [145]:
resampled_data['total_pickups'].ewm(alpha=0.9).mean()

tpep_pickup_datetime
2016-01-01 00:00:00     58.000000
2016-01-01 00:15:00    114.363636
2016-01-01 00:30:00    145.567568
2016-01-01 00:45:00    158.558056
2016-01-01 01:00:00    184.156062
                          ...
2016-03-31 22:45:00     14.720768
2016-03-31 23:00:00     16.772077
2016-03-31 23:15:00     17.877208
2016-03-31 23:30:00     13.487721
2016-03-31 23:45:00     13.948772
Name: total_pickups, Length: 262080, dtype: float64

In [146]:

smoothing_values = np.arange(0.2,1,0.1)
smoothing_values

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [147]:

def calculate_best_smoothing_value(values):
    y = resampled_data['total_pickups'].values
    for value in values:
        y_pred = resampled_data['total_pickups'].ewm(alpha=value).mean()
        error = mean_absolute_percentage_error(y, y_pred)
        print(f"For smoothing value {value:.1f}, the MAPE is {error:.2f}")

In [148]:

calculate_best_smoothing_value(smoothing_values)

For smoothing value 0.2, the MAPE is 0.41
For smoothing value 0.3, the MAPE is 0.27
For smoothing value 0.4, the MAPE is 0.20
For smoothing value 0.5, the MAPE is 0.16
For smoothing value 0.6, the MAPE is 0.12
For smoothing value 0.7, the MAPE is 0.09
For smoothing value 0.8, the MAPE is 0.06
For smoothing value 0.9, the MAPE is 0.03

In [149]:

# dataset with pickup smoothing applied (shifted by 1 to avoid data leakage)

resampled_data["avg_pickups"] = resampled_data['total_pickups'].ewm(alpha=0.4).mean().shift(1).round()

resampled_data

                      region  total_pickups  avg_pickups
tpep_pickup_datetime
2016-01-01 00:00:00        0             58          NaN
2016-01-01 00:15:00        0            120         58.0
2016-01-01 00:30:00        0            149         97.0
2016-01-01 00:45:00        0            160        123.0
2016-01-01 01:00:00        0            187        140.0
...                      ...            ...          ...
2016-03-31 22:45:00       29             14         17.0
2016-03-31 23:00:00       29             17         16.0
2016-03-31 23:15:00       29             18         16.0
2016-03-31 23:30:00       29             13         17.0
2016-03-31 23:45:00       29             14         15.0

[262080 rows x 3 columns]

In [150]:

# save the resampled data

resampled_data_save_path = "/kaggle/working/data/interim/final_data.csv"

resampled_data.to_csv(resampled_data_save_path, index=True)

## Model Building

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# load the data

data_path = "/kaggle/working/data/interim/final_data.csv"

df = pd.read_csv(data_path, parse_dates=["tpep_pickup_datetime"])

In [2]:
# shape of the data

df.shape

(262080, 4)

In [3]:

# extract the day of week information
df["day_of_week"] = df["tpep_pickup_datetime"].dt.day_of_week

# extract the month information
df["month"] = df["tpep_pickup_datetime"].dt.month

In [4]:
# set the datetime column as index

df.set_index("tpep_pickup_datetime", inplace=True)
df

                      region  total_pickups  avg_pickups  day_of_week  month
tpep_pickup_datetime
2016-01-01 00:00:00        0             58          NaN            4      1
2016-01-01 00:15:00        0            120         58.0            4      1
2016-01-01 00:30:00        0            149         97.0            4      1
2016-01-01 00:45:00        0            160        123.0            4      1
2016-01-01 01:00:00        0            187        140.0            4      1
...                      ...            ...          ...          ...    ...
2016-03-31 22:45:00       29             14         17.0            3      3
2016-03-31 23:00:00       29             17         16.0            3      3
2016-03-31 23:15:00       29             18         16.0            3      3
2016-03-31 23:30:00       29             13         17.0            3      3
2016-03-31 23:45:00       29             14         15.0            3      3

[262080 rows x 5 columns]

In [5]:
# create the region grouper

region_grp = df.groupby("region")

region_grp.

In [6]:
# shifting periods

periods = list(range(1,5))

periods

[1, 2, 3, 4]

In [7]:
# generate the lag features

lag_features = region_grp["total_pickups"].shift(periods)

lag_features

,total_pickups_1,total_pickups_2,total_pickups_3,total_pickups_4
tpep_pickup_datetime,,,,
2016-01-01 00:00:00,NaN,NaN,NaN,NaN
2016-01-01 00:15:00,58.0,NaN,NaN,NaN
2016-01-01 00:30:00,120.0,58.0,NaN,NaN
2016-01-01 00:45:00,149.0,120.0,58.0,NaN
2016-01-01 01:00:00,160.0,149.0,120.0,58.0
...,...,...,...,...
2016-03-31 22:45:00,22.0,14.0,15.0,13.0
2016-03-31 23:00:00,14.0,22.0,14.0,15.0
2016-03-31 23:15:00,17.0,14.0,22.0,14.0
2016-03-31 23:30:00,18.0,17.0,14.0,22.0
2016-03-31 23:45:00,13.0,18.0,17.0,14.0

In [8]:
# merge them with the original df

data = pd.concat([lag_features,df],axis=1)

data

,total_pickups_1,total_pickups_2,total_pickups_3,total_pickups_4,region,total_pickups,avg_pickups,day_of_week,month
tpep_pickup_datetime,,,,,,,,,
2016-01-01 00:00:00,NaN,NaN,NaN,NaN,0,58,NaN,4,1
2016-01-01 00:15:00,58.0,NaN,NaN,NaN,0,120,58.0,4,1
2016-01-01 00:30:00,120.0,58.0,NaN,NaN,0,149,97.0,4,1
2016-01-01 00:45:00,149.0,120.0,58.0,NaN,0,160,123.0,4,1
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,140.0,4,1
...,...,...,...,...,...,...,...,...,...
2016-03-31 22:45:00,22.0,14.0,15.0,13.0,29,14,17.0,3,3
2016-03-31 23:00:00,14.0,22.0,14.0,15.0,29,17,16.0,3,3
2016-03-31 23:15:00,17.0,14.0,22.0,14.0,29,18,16.0,3,3
2016-03-31 23:30:00,18.0,17.0,14.0,22.0,29,13,17.0,3,3
2016-03-31 23:45:00,13.0,18.0,17.0,14.0,29,14,15.0,3,3

In [9]:
print("The shape of the df before merger ", df.shape)
print("The shape of the df after merger ", data.shape)

The shape of the df before merger  (262080, 5)
The shape of the df after merger  (262080, 9)

In [10]:
# rows having missing values

data.isna().any(axis=1).sum()

np.int64(120)

In [11]:
# drop the missing values

data.dropna(inplace=True)
data.isna().any(axis=1).sum()

np.int64(0)

In [12]:
mapper = {name:f"lag_{ind+1}" for ind, name in enumerate(data.columns[0:4])}

mapper

{'total_pickups_1': 'lag_1',
 'total_pickups_2': 'lag_2',
 'total_pickups_3': 'lag_3',
 'total_pickups_4': 'lag_4'}

In [13]:
# replace the column names

data = data.rename(columns=mapper)

In [14]:
# number of rows in each month

data['month'].value_counts()

month
3    89280
1    89160
2    83520
Name: count, dtype: int64

In [15]:
data.loc[data["month"].isin([1,2]),"lag_1":"day_of_week"]

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,140.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,161.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,175.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,177.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,12.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,14.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,15.0,0

In [16]:
# split the data

trainset = data.loc[data["month"].isin([1,2]),"lag_1":"day_of_week"]

testset = data.loc[data["month"].isin([3]),"lag_1":"day_of_week"]
trainset

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,140.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,161.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,175.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,177.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,12.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,14.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,15.0,0

In [21]:
# save the train and test data

train_data_save_path = "/kaggle/working/data/interim/train.csv"

test_data_save_path = "/kaggle/working/data/interim/test.csv"

trainset.to_csv(train_data_save_path, index=True)
testset.to_csv(test_data_save_path, index=True)

In [22]:
# make X_train and y_train

X_train = trainset.drop(columns=["total_pickups"])

y_train = trainset["total_pickups"]

In [23]:
X_train.shape

(172680, 7)

In [25]:
y_train.shape

(172680,)

In [30]:
# make X_test and y_test

X_test = testset.drop(columns=["total_pickups"])

y_test = testset["total_pickups"]

In [26]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_percentage_error

In [27]:
from sklearn import set_config

set_config(transform_output="pandas")

In [28]:

# encode the data

encoder = ColumnTransformer([
    ("ohe", OneHotEncoder(drop="first",sparse_output=False), ["region","day_of_week"])
], remainder="passthrough", n_jobs=-1,force_int_remainder_cols=False)

In [31]:
# encode the train and test data

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

In [32]:
# encode the train and test data

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

In [33]:
# train the model

lr = LinearRegression()

# fit on the training data
lr.fit(X_train_encoded, y_train)

LinearRegression()

In [37]:
# make predictions on the train data

y_pred_train = lr.predict(X_train_encoded)
# make predictions on the test data

y_pred_test = lr.predict(X_test_encoded)

In [38]:
# evaluate the baseline model

train_mape = mean_absolute_percentage_error(y_train, y_pred_train)

test_mape = mean_absolute_percentage_error(y_test, y_pred_test)

In [39]:
test_mape

0.30698710068880253

In [40]:
print(f"MAPE on trainset is {(train_mape * 100):.2f}%")
print(f"MAPE on testset is {(test_mape * 100):.2f}%")

MAPE on trainset is 31.75%
MAPE on testset is 30.70%

## Hyper Parmeter tuning

In [2]:
!pip install mlflow

Collecting mlflow
  Downloading mlflow-3.16.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 1.7 MB/s eta 0:00:00
Collecting mlflow-skinny==3.16.0 (from mlflow)
  Downloading mlflow_skinny-3.16.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 1.9 MB/s eta 0:00:00
Collecting mlflow-tracing==3.16.0 (from mlflow)
  Downloading mlflow_tracing-3.16.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<51,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.1.0)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow)
  Downloading gunicorn-26.2.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<26,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (24.0.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.49)
Requirement already satisfied: anyio!=4.15.0,<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (4.13.0)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (8.3.3)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading databricks_sdk-0.136.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.2/44.2 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (0.136.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (3.1.47)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (26.1)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (5.29.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.16.0->mlflow) (0.46.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.23.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.11)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<51,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.12-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4->mlflow) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.4.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.16.0->mlflow) (3.13)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<51,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (2.47.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.16.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.16.0->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.16.0->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.16.0->mlflow) (3.23.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.16.0->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.0->mlflow) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.0->mlflow) (3.4.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.0->mlflow) (2026.4.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.16.0->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.16.0->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (0.6.3)
Downloading mlflow-3.16.0-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 62.1 MB/s eta 0:00:00:00:010:01
Downloading mlflow_skinny-3.16.0-py3-none-any.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 72.0 MB/s eta 0:00:00:00:01
Downloading mlflow_tracing-3.16.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 39.3 MB/s eta 0:00:00:00:01
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 4.0 MB/s eta 0:00:00
Downloading gunicorn-26.2.0-py3-none-any.whl (228 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.4/228.4 kB 9.9 MB/s eta 0:00:00
Downloading huey-3.4.0-py3-none-any.whl (136 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.5/136.5 kB 6.8 MB/s eta 0:00:00
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 4.5 MB/s eta 0:00:00
Downloading databricks_sdk-0.136.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 25.7 MB/s eta 0:00:0000:01
Downloading graphql_core-3.2.12-py3-none-any.whl (216 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.0/216.0 kB 10.3 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Installing collected packages: huey, gunicorn, graphql-core, graphql-relay, skops, graphene, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
Successfully installed Flask-CORS-6.0.5 databricks-sdk-0.136.0 graphene-3.4.3 graphql-core-3.2.12 graphql-relay-3.2.0 gunicorn-26.2.0 huey-3.4.0 mlflow-3.16.0 mlflow-skinny-3.16.0 mlflow-tracing-3.16.0 skops-0.14.0

In [3]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.svm import SVR

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

import mlflow

In [4]:
mlflow.set_tracking_uri("https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow")

In [7]:
!pip install dagshub

Collecting dagshub
  Downloading dagshub-0.7.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: PyYAML>=5 in /usr/local/lib/python3.12/dist-packages (from dagshub) (6.0.3)
Collecting appdirs>=1.4.4 (from dagshub)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: click>=8.0.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (8.3.3)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: GitPython>=3.1.29 in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.1.47)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Collecting dacite~=1.6.0 (from dagshub)
  Downloading dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Collecting gql[requests] (from dagshub)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.6.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.3.3)
Collecting treelib>=1.6.4 (from dagshub)
  Downloading treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.43.36)
Collecting semver (from dagshub)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.2.0 (from dagshub)
  Downloading dagshub_annotation_converter-0.2.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (2.12.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from GitPython>=3.1.29->dagshub) (4.0.12)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from treelib>=1.6.4->dagshub) (1.17.0)
Requirement already satisfied: botocore<1.44.0,>=1.43.36 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.43.36)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (0.19.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: graphql-core<3.3,>=3.2 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (3.2.12)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.23.0)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests<3,>=2.26 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (2.32.4)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->dagshub) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->dagshub) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->dagshub) (2026.1)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.44.0,>=1.43.36->boto3->dagshub) (2.5.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.29->dagshub) (5.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.12/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->dagshub) (26.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.26->gql[requests]->dagshub) (3.4.7)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (0.4.1)
Downloading dagshub-0.7.2-py3-none-any.whl (273 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.0/274.0 kB 8.1 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Downloading dagshub_annotation_converter-0.2.2-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 3.1 MB/s eta 0:00:00
Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)
Downloading treelib-1.8.0-py3-none-any.whl (30 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 4.5 MB/s eta 0:00:00
Installing collected packages: appdirs, treelib, semver, pathvalidate, dacite, backoff, gql, dagshub-annotation-converter, dagshub
  Attempting uninstall: dacite
    Found existing installation: dacite 1.9.2
    Uninstalling dacite-1.9.2:
      Successfully uninstalled dacite-1.9.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.4 requires dacite<2,>=1.9, but you have dacite 1.6.0 which is incompatible.
Successfully installed appdirs-1.4.4 backoff-2.2.1 dacite-1.6.0 dagshub-0.7.2 dagshub-annotation-converter-0.2.2 gql-4.0.0 pathvalidate-3.3.1 semver-3.0.4 treelib-1.8.0

In [8]:
import dagshub
dagshub.init(repo_owner='iamdebasishdas123', repo_name='Uber-Demand-Prediction', mlflow=True)

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=1c2052ca-96c0-4670-9792-d1f0ae52e197&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=2a46cac39779d8c298776ddbb359eac8fb7db29ffe3447ec52c20465793e31fc

Accessing as iamdebasishdas123

Initialized MLflow to track repo "iamdebasishdas123/Uber-Demand-Prediction"

Repository iamdebasishdas123/Uber-Demand-Prediction initialized!

In [10]:
# load the training and test data

train_data_path = "/kaggle/working/data/interim/train.csv"

test_data_path = "/kaggle/working/data/interim/test.csv"

train_df = pd.read_csv(train_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

test_df = pd.read_csv(test_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

train_df

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,140.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,161.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,175.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,177.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,12.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,14.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,15.0,0

In [11]:
# missing value in training data

train_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [12]:
# missing values in the test data

test_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [13]:
# make X_train and y_train

X_train = train_df.drop(columns=["total_pickups"])

y_train = train_df["total_pickups"]

In [15]:

X_test.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-03-01 00:00:00,36.0,44.0,31.0,29.0,0,38.0,1
2016-03-01 00:15:00,41.0,36.0,44.0,31.0,0,39.0,1
2016-03-01 00:30:00,35.0,41.0,36.0,44.0,0,37.0,1
2016-03-01 00:45:00,47.0,35.0,41.0,36.0,0,41.0,1
2016-03-01 01:00:00,34.0,47.0,35.0,41.0,0,38.0,1

In [16]:
from sklearn import set_config

set_config(transform_output="pandas")

# encode the data

encoder = ColumnTransformer([
    ("ohe", OneHotEncoder(drop="first",sparse_output=False), ["region","day_of_week"])
], remainder="passthrough", n_jobs=-1,force_int_remainder_cols=False)

In [17]:
encoder

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['region', 'day_of_week'])])

In [18]:
# encode the train and test data

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

In [19]:
import optuna
import tqdm

In [20]:
# set the experiment

mlflow.set_experiment("Model Selection")

2026/09/07 17:17:10 INFO mlflow.tracking.fluent: Experiment with name 'Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/633924a0084f421b8ee9308ded20e23c', creation_time=1788801430355, effective_trace_archival_retention=None, experiment_id='0', last_update_time=1788801430355, lifecycle_stage='active', name='Model Selection', tags={}, trace_location=None, workspace='default'>

*OPtuna*
Optuna works by framing hyperparameter optimization as an iterative search problem where a central orchestrator decides which parameter combinations to test based on past performance.

To build an Optuna optimization script, you only need four core components:

- An Objective Function: A standard Python function that accepts an Optuna trial object as its input.
It must contain your data loading, model initialization, training loop, and evaluation step.
- Suggested Hyperparameters: Inside your objective function, you must replace your fixed numbers with Optuna suggestion methods.Examples: trial.suggest_float(), trial.suggest_int(), or trial.suggest_categorical().
- A Return Metric: Your objective function must return a single scalar value (a float) at the very end.This is the metric Optuna will look at to judge whether the trial was a success or a failure.
- A Study Object: Generated via optuna.create_study().You must explicitly tell it whether to maximize your return metric (e.g., accuracy, F1-score) or minimize it (e.g., MSE loss, cross-entropy).

In [21]:
def objective(trial):
    # start the child run
    with mlflow.start_run(nested=True) as child:
        
        # model name search space
        list_of_models = ["LR", "RF", "GBR", "XGBR"]
        model_name = trial.suggest_categorical("model_name", list_of_models)
    
        if model_name == "LR":
            model = LinearRegression()
    
        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,100,step=10)
            max_depth_rf = trial.suggest_int("max_depth_rf",3,10)
            model = RandomForestRegressor(n_estimators=n_estimators_rf, 
                                          max_depth=max_depth_rf, 
                                          random_state=42, n_jobs=-1)
    
        elif model_name == "GBR":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,100,step=10)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",1e-4,1e-1, log=True)
            model = GradientBoostingRegressor(n_estimators=n_estimators_gb, 
                                              learning_rate=learning_rate_gb,
                                             random_state=42)
    
        elif model_name == "XGBR":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,100,step=10)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",1e-4,1e-1, log=True)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",3,10)
            model = XGBRegressor(n_estimators=n_estimators_xgb,
                                learning_rate=learning_rate_xgb,
                                max_depth=max_depth_xgb)
    
        # log the model name
        mlflow.log_param("model_name",model_name)
        
        # log the model parameters
        mlflow.log_params(model.get_params())
        
        # fit on the data
        model.fit(X_train_encoded,y_train)
    
        # get the predictions
        y_pred = model.predict(X_test_encoded)
    
        # calculate the loss
        loss = mean_absolute_percentage_error(y_test, y_pred)
    
        # log the metric
        mlflow.log_metric("MAPE",loss)
        return loss

In [22]:
# optimize the objective function

with mlflow.start_run(run_name="best_model", nested=True) as parent:

    # create a study object
    study = optuna.create_study(study_name="model_selection", direction="minimize")
    # optimize the objective function
    study.optimize(func=objective, n_trials=50, n_jobs=-1)
    
    # log the best parameters
    mlflow.log_params(study.best_params)
    # log the best error value
    mlflow.log_metric("Best_MAPE", study.best_value)

[I 2026-09-07 17:17:46,799] A new study created in memory with name: model_selection
[I 2026-09-07 17:18:10,655] Trial 1 finished with value: 6.087102890014648 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 70, 'learning_rate_xgb': 0.0011387586709509074, 'max_depth_xgb': 5}. Best is trial 1 with value: 6.087102890014648.

🏃 View run fearless-kite-372 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/969e6cd6d1374c6781eb79912a95933a
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:18:17,455] Trial 3 finished with value: 0.3252742186859445 and parameters: {'model_name': 'RF', 'n_estimators_rf': 100, 'max_depth_rf': 5}. Best is trial 3 with value: 0.3252742186859445.

🏃 View run beautiful-stoat-152 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/dfc66fe58cfd4bc287beb70d7a4cf6a4
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:18:28,239] Trial 4 finished with value: 6.446369647979736 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 70, 'learning_rate_xgb': 0.0002952632025340156, 'max_depth_xgb': 6}. Best is trial 3 with value: 0.3252742186859445.

🏃 View run stately-squid-788 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/08e5f2388c774fe6bda04d51a3b445f0
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:18:29,962] Trial 6 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run gifted-shoat-9 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/a70f0d17df1b4f6287707e3c39906ac0
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:18:31,382] Trial 7 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run wise-bear-396 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/cd2b7d936c494b7ba98ab2a595f0d0d4
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run defiant-panda-647 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/24b453f0c99d4b14a86d9007dc61313f
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:18:38,986] Trial 2 finished with value: 0.7455787004872559 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 50, 'learning_rate_gb': 0.05209796742988936}. Best is trial 6 with value: 0.30698710068880253.
[I 2026-09-07 17:18:39,296] Trial 8 finished with value: 6.503714561462402 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 90, 'learning_rate_xgb': 0.00013035774576966968, 'max_depth_xgb': 4}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run overjoyed-horse-342 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/b02d449b510a403ba774fc7d77da347f
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run trusting-lark-496 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/67c45c95f1a347d1a065642e0381ed11
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run unruly-shrimp-30 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/1a199336907144d0a1a3e57ba0bb95f6
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:18:59,256] Trial 5 finished with value: 6.09288401968163 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 70, 'learning_rate_gb': 0.0011654373821197459}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run industrious-hare-297 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/2001e2dc54c74843b63137ecb9ddcaf3
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:19:03,027] Trial 9 finished with value: 6.487967014312744 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 60, 'learning_rate_xgb': 0.00023441966004918673, 'max_depth_xgb': 6}. Best is trial 6 with value: 0.30698710068880253.
[I 2026-09-07 17:19:06,440] Trial 12 finished with value: 6.221295356750488 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.005701709779706737, 'max_depth_xgb': 7}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run powerful-crane-136 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/db4c203cdcb34940bae9d4765a4ae415
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:19:07,000] Trial 0 finished with value: 6.479676614788066 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 80, 'learning_rate_gb': 0.00019939255342296902}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run marvelous-horse-403 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/0461711bafae47d5a0d129f894ccbf2f
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run overjoyed-yak-365 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/99ac57d2f0a84eb1aa26e34641a8a7ea
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:19:27,030] Trial 10 finished with value: 5.1890692710876465 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 60, 'learning_rate_xgb': 0.004120774626162243, 'max_depth_xgb': 4}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run agreeable-duck-46 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/ce5ca030ec334b8bb320449785b1a353
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:19:39,017] Trial 14 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run beautiful-loon-162 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/239ccc6a4a364989836d3433481efdc6
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:19:50,975] Trial 13 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.
[I 2026-09-07 17:19:56,213] Trial 16 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run victorious-lark-971 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/8faf8ee96ad741e5b58cc3b04eaf9512
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run gaudy-hound-245 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/207ea02b410547f0b973d8cdb268eed0
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:20:02,981] Trial 11 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.
[I 2026-09-07 17:20:10,990] Trial 15 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.
[I 2026-09-07 17:20:15,254] Trial 18 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run bemused-wolf-129 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/a8627ada87c44c1cb65deeea8734fbca
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run lyrical-grouse-337 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/0f409e289e874d1f82395fd89f56f5c8
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:20:35,055] Trial 17 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run angry-goose-364 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/91b8bca7087a4926bd449c8f1fb9ce81
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:20:39,519] Trial 19 finished with value: 0.30698710068880253 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068880253.

🏃 View run calm-snipe-868 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/da7ced8e9f3e4ce8866bc9078879697b
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run victorious-mouse-939 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/5c9b6d0c508b45c694a3f975df3f1f79
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:20:59,284] Trial 20 finished with value: 0.2896603056728178 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 20 with value: 0.2896603056728178.

🏃 View run resilient-eel-816 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/453075f7b47a4373b7c40f45644138c7
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:21:03,000] Trial 21 finished with value: 0.2896069414536356 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 21 with value: 0.2896069414536356.
[I 2026-09-07 17:21:07,037] Trial 22 finished with value: 0.2896603056728178 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 21 with value: 0.2896069414536356.
[I 2026-09-07 17:21:13,825] Trial 23 finished with value: 0.2896603056728178 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 21 with value: 0.2896069414536356.

🏃 View run awesome-crab-926 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/07fafdb78d7a4de5a4282192c494a68d
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:21:22,827] Trial 25 finished with value: 0.2896603056728178 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 21 with value: 0.2896069414536356.

🏃 View run clean-worm-471 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/df67ac4577d04f8d8893143a9e6aecf1
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run salty-dolphin-271 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/146f3edb335844e280e7bb3fc42b8781
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:21:46,688] Trial 24 finished with value: 0.2896603056728178 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 21 with value: 0.2896069414536356.
[I 2026-09-07 17:21:59,082] Trial 28 finished with value: 0.2896069414536355 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run traveling-auk-600 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/c2eb25cc11a9438bb1a03452faff7737
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:22:02,236] Trial 29 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run inquisitive-croc-370 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/9951b430b7bd4744aef3adb7b9301284
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run bright-worm-203 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/9f7a4a66ff1544ca995b2a1e02d9f989
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run rogue-crane-134 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/28ab5f749e1a4040b0fe08f8bd269985
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:22:11,044] Trial 27 finished with value: 0.2896603056728178 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.
[I 2026-09-07 17:22:15,060] Trial 26 finished with value: 0.2896069414536355 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run invincible-shrew-738 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/60958db87eff496e8f1bc84f1309afce
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:22:35,078] Trial 31 finished with value: 0.29635635575980007 and parameters: {'model_name': 'RF', 'n_estimators_rf': 40, 'max_depth_rf': 8}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run stately-flea-522 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/0be537201ca5416ba070b4e5673a6f39
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:22:51,159] Trial 30 finished with value: 0.2963287855529188 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 8}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run salty-boar-806 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/87dad25f08034013a1ef78d31b103c0b
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run industrious-yak-444 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/db8a58f04f4247e1b3097ae13aa608af
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:23:07,058] Trial 32 finished with value: 0.29635635575980007 and parameters: {'model_name': 'RF', 'n_estimators_rf': 40, 'max_depth_rf': 8}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run blushing-hawk-103 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/0c62060eb79640089459ab4ed1c62089
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:23:18,021] Trial 36 finished with value: 0.29273230925411237 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 9}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run honorable-hound-984 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/e31cedfafdaa4340975d0fa6fb11157b
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:23:19,069] Trial 33 finished with value: 0.29635635575980007 and parameters: {'model_name': 'RF', 'n_estimators_rf': 40, 'max_depth_rf': 8}. Best is trial 28 with value: 0.2896069414536355.
[I 2026-09-07 17:23:22,998] Trial 35 finished with value: 0.2963463016961937 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 8}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run abrasive-rat-555 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/d1f4ea38c37f4d84b05fdd19ef37f7f5
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:23:23,103] Trial 34 finished with value: 0.2963463016961937 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 8}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run gregarious-swan-172 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/c7639f349bba4517b53f00a7e6fb825e
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:23:42,758] Trial 37 finished with value: 2.912839782972349 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.08636234801651439}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run bright-robin-286 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/36e28bb902cb463fbc9480db9696b0ae
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run casual-doe-536 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/1bfc0cd883c14e789d7a1778b065b3f0
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:23:51,147] Trial 38 finished with value: 3.412286281030857 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.06916114233458012}. Best is trial 28 with value: 0.2896069414536355.
[I 2026-09-07 17:23:55,084] Trial 40 finished with value: 2.7109652423191744 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.09393551153433338}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run masked-squirrel-818 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/ac6d9887eb254411a9b0f469ceb19657
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:24:03,080] Trial 39 finished with value: 2.8095032154363753 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.08910950594827881}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run persistent-finch-835 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/5ae0b75e1f444cf9898cea42ed53182d
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:24:19,371] Trial 42 finished with value: 0.29259642609457387 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 9}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run flawless-pig-873 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/83c6b29dd9984b2e85c091ae8d95c652
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:24:27,371] Trial 43 finished with value: 0.29259642609457387 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 9}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run caring-bear-946 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/33e24b5e088042a995d0277bf4807f74
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:24:30,757] Trial 41 finished with value: 6.314410245766534 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.004340298572260174}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run secretive-hawk-343 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/2869e7d99b194a24b622388cf61f9286
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:24:47,146] Trial 44 finished with value: 0.29259642609457387 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 9}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run marvelous-sloth-992 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/558490d7cb684cefae9edde9720b0650
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run resilient-toad-715 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/fbb692e146ca49358f0f9e3747ce0187
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:25:06,769] Trial 45 finished with value: 0.2896069414536356 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.
[I 2026-09-07 17:25:07,105] Trial 47 finished with value: 0.2896069414536356 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run monumental-trout-153 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/e9eaadf58ee14ed59b59e37c6eb7d3e8
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run ambitious-quail-790 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/703167fefb8746f191dcb88c270c0471
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

[I 2026-09-07 17:25:18,775] Trial 48 finished with value: 0.2896069414536355 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.
[I 2026-09-07 17:25:19,131] Trial 46 finished with value: 0.2896069414536356 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 28 with value: 0.2896069414536355.
[I 2026-09-07 17:25:27,909] Trial 49 finished with value: 0.29259642609457387 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 9}. Best is trial 28 with value: 0.2896069414536355.

🏃 View run shivering-deer-320 at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/4211401b16ee42479d026386eb2f7a33
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0
🏃 View run best_model at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0/runs/43a17cb9748848e293386e0691674fbc
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/Uber-Demand-Prediction.mlflow/#/experiments/0

In [23]:
# best value

study.best_value

0.2896069414536355

In [24]:
# best parameters

study.best_params

{'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}

In [25]:
# model value counts

study.trials_dataframe()['params_model_name'].value_counts()

params_model_name
RF      26
LR      10
GBR      8
XGBR     6
Name: count, dtype: int64